"""Store protocol: incidents, alerts, triage, response_actions, intake_state."""
from typing import Optional, Protocol


class Store(Protocol):
    def list_alerts(
        self, *, severity: Optional[str] = None, host: Optional[str] = None,
        limit: int = 50, since: Optional[str] = None,
    ) -> list[dict]: ...

    def list_incidents(
        self, *, severity: Optional[str] = None, host: Optional[str] = None,
        limit: int = 50, since: Optional[str] = None, order: str = "desc",
    ) -> list[dict]: ...

    def get_incident(self, incident_id: str) -> Optional[dict]: ...

    def get_alerts_by_ids(self, alert_ids: list[str]) -> list[dict]: ...

    def get_triage(self, incident_id: str) -> Optional[dict]: ...

    def save_triage(self, triage: dict) -> None: ...

    def list_response_actions(self, incident_id: str) -> list[dict]: ...

    def get_latest_response_action(self, incident_id: str) -> Optional[dict]: ...

    def list_all_response_actions(self) -> list[dict]: ...

    def get_response_action(self, action_id: str) -> Optional[dict]: ...

    def save_response_action(self, action: dict) -> None: ...

    def update_response_action(self, action_id: str, updates: dict) -> Optional[dict]: ...

    def list_pending_commands(self, host: str) -> list[dict]: ...

    def get_intake_state(self) -> dict: ...

    def save_intake_state(self, state: dict) -> None: ...

    # --- Metrics page (read-only; no since upper bound, "now" is implicit) ---

    def count_alerts(self, *, since: Optional[str] = None, severity: Optional[str] = None) -> int: ...

    def count_incidents(self, *, since: Optional[str] = None, severity: Optional[str] = None) -> int: ...

    def alerts_timeseries(self, *, since: Optional[str], interval: str) -> list[dict]: ...

    def alerts_top_terms(self, field: str, *, since: Optional[str] = None, size: int = 5) -> list[dict]: ...

    def alerts_by_technique_tactic(self, *, since: Optional[str] = None) -> list[dict]: ...

    def list_all_triage(self, *, since: Optional[str] = None) -> list[dict]: ...

    def index_health(self, index_name: str) -> Optional[dict]: ...
